name: "Homie"
description: "A household inventory app"
version: "1.4.1"
slug: "homie"
image: ghcr.io/kmayne/homie
init: false
startup: application
boot: auto
arch:
  - aarch64
  - amd64
ports:
  3000/tcp: 3000
webui: http://[HOST]:[PORT:3000]
options:
  origins: []
schema:
  origins:
    - url
